---
- hosts: managesf
  gather_facts: no
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/stopsfservices.yml
  # Synchronize the FS with eDeploy
  - name: Synchronize FS with eDeploy
    command: edeploy upgrade {{ version }}
