hosts:
  localhost:
    ip: 127.0.0.1
  puppetmaster:
    ip: 94.143.114.183 
    host_aliases: ['sf-puppetmaster', 'puppetmaster.pub']
  mysql:
    ip: 46.231.128.61
    host_aliases: ['sf-mysql', 'mysql.pub']
  ldap:
    ip: 46.231.128.44
    host_aliases: ['sf-ldap', 'ldap.pub']
  redmine:
    ip: 46.231.128.11
    host_aliases: ['sf-redmine', 'redmine.pub']
  jenkins:
    ip: 46.231.128.53
    host_aliases: ['sf-jenkins', 'jenkins.pub']
  gerrit:
    ip: 46.231.128.45
    host_aliases: ['sf-gerrit', 'gerrit.pub']
