pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment_filter: retrigger
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
  - name: post
    description: Changes merged enter this pipeline.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: change-merged
    success:
      gerrit:
        force-message: True
    failure:
      gerrit:
        force-message: True

projects:
  - name: config
    check:
      - config-check
    post:
      - config-update
  - name: zuul-demo
    check:
      - zuul-demo-functional-tests
      - zuul-demo-unit-tests
